# Generated by Django 3.2.9 on 2022-05-23 14:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=30)),
                ('category', models.CharField(choices=[('MANAGEMENT', 'Management'), ('SOFTWARE', 'Software Development'), ('UXUI', 'UX/UI Design'), ('OTHER', 'Other')], default='OTHER', max_length=15)),
                ('urgency', models.CharField(choices=[('HIGH', 'High'), ('INTERMEDIATE', 'Intermediate'), ('LOW', 'Low')], default='OTHER', max_length=15)),
                ('due_date', models.DateField()),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
